### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by Mealoore** [HKUST-Aerial-Robotics/FIESTA#14]
when running the demo－"cow and lady",why do I meet this problem:
================================================================================REQUIRED process [fiesta-2] has died!
process has died [pid 11418, exit code -11, cmd /home/qjp/Backup/Lib/My_Fiesta/devel/lib/fiesta/test_fiesta ~depth:=/camera/depth_registered/points ~transform:=/kinect/vrpn_client/estimated_transform __name:=fiesta __log:=/home/qjp/.ros/log/369c6134-9cf0-11ea-8da5-d0577bdd6576/fiesta-2.log].
log file: /home/qjp/.ros/log/369c6134-9cf0-11ea-8da5-d0577bdd6576/fiesta-2*.log
Initiating shutdown!
================================================================================

**Comment by marcuswuh** [comment]
Same problem

**Comment by marcuswuh** [comment]
Solved This Problem.
The default param "Fixed Frame" in rviz is "map" or sth else.
But this prj should set this param to "world".

**Comment by ZWT006** [comment]
I have sen the presumably problem recently. But can't solver this problem by setting rviz default param "Fixed Frame" to "world".

`================================================================================REQUIRED process [fiesta-1] has died!
process has died [pid 15413, exit code -11, cmd /home/zwt/ctrl_ws/devel/lib/fiesta/test_fiesta ~depth:=/camera/depth_registered/points ~transform:=/kinect/vrpn_client/estimated_transform __name:=fiesta __log:=/home/zwt/.ros/log/4298e576-328e-11ed-865b-d0c5d35f6a67/fiesta-1.log].
log file: /home/zwt/.ros/log/4298e576-328e-11ed-865b-d0c5d35f6a67/fiesta-1*.log
Initiating shutdown!
================================================================================`

**Comment by ZWT006** [comment]
I change an other  PC，and install this package, than everyting is fine. The cow_and_lady.bag runs well
