### ISSUE TITLE
About Lidar Input

### ISSUE THREAD

**Issue by Robinaoko** [HKUST-Aerial-Robotics/FIESTA#16]
How to use Lidar such as VLP16 as input？

**Comment by Robinaoko** [comment]
Can Fiesta only subscribe from depth and transform？

**Comment by hlx1996** [comment]
No, please read the paper & the code carefully.
From version 0.4.0, FIEST supports LIDAR input officially

**Comment by cdefg** [comment]
I am trying to adapt FIESTA to Lidar input in gazebo simulation.
But I can’t do this well, and got wrong occ at first.

result: <img width="912" alt="image" src="https://github.com/user-attachments/assets/8991b66f-8680-46ad-8d3f-b4945fd5fa86">
To realize occ building target, I mimic cow and lady dataset, especially frame transforms.
I have no idea now.
Do you have any idea? @hlx1996
