### ISSUE TITLE
Saving the ESDF map

### ISSUE THREAD

**Issue by deepak-1530** [HKUST-Aerial-Robotics/FIESTA#21]
I want to save the ESDF map generated by FIESTA. Is there a way to do it?

**Comment by hlx1996** [comment]
If you just want to save ESDF map itself, you can only dump the vector distance_buffer_.
If you want the saved map can be reused in FIESTA, I suggest you save the following vectors at Line 82 - 91 in ESDFMap.h
https://github.com/HKUST-Aerial-Robotics/FIESTA/blob/master/include/ESDFMap.h#L82
