### ISSUE TITLE
REQUIRED process [fiesta-2] has died!

### ISSUE THREAD

**Issue by IngaVS** [HKUST-Aerial-Robotics/FIESTA#6]
I has run FIESTA successfully, and then I run other project that maybe lead to the environment changed.But I can't find reason of the error.

I run the code:
catkin_make 
source ~/catkin_ws/devel/setup.bash 
roslaunch fiesta cow_and_lady.launch 
rosbag play data.bag
![Screenshot from 2019-10-10 21-29-49](https://user-images.githubusercontent.com/18420049/66617634-806c8580-ec08-11e9-9b68-0567490dd362.png)

I checke the version
PCL is 1.7.2
OPenCV is 3.4.3
Eigen 3.3.0

**Comment by USTfgaoaa** [comment]
@hlx1996

**Comment by hlx1996** [comment]
Sorry, @IngaVS , I cannot get enough effective information to replicate the issue you encountered.
If you have not solved it yet, could you please describe your issue more clearly?
BTW, it will be very helpful to use print functions to locate in which step FIESTA crashed.
Thanks.

**Comment by v1otusc** [comment]
Hi, same issue as yours, @IngaVS have you work it out？
