### ISSUE TITLE
Why use a self-defined hash function

### ISSUE THREAD

**Issue by JINXER000** [HKUST-Aerial-Robotics/FIESTA#9]
Dear author, I found it confusing in ESDFMap.h:24, where `MatrixHash` is defined. Why you designed the hash function like this, using transform as input to compute the hash value? What is the benefit?
Thanks.

**Comment by hlx1996** [comment]
Hello,
The hash function is just a simple hash function that maps a matrix to an
integer.
In FIESTA, the only usage of this hash function is to map a 3D voxel
coordinate to the index of the Voxel Information Structure.


陈奕州 <notifications@github.com> 于2020年1月13日周一 下午10:40写道：
